openapi: 3.0.3
info:
  title: Pages
  description: This API is responsible for CRUD operations of websites
  version: 1.0.0
  contact:
    email: istvan.percsi.de@gmail.com
  license:
    name: Apache 2.0
servers:
  - url: 'http://localhost:8080/v1/'
tags:
  - name: page
    description: Page Administration

paths:
  /pages/{pageId}:
    get:
      tags:
        - page
      summary: Get a page
      description: Get page, if parameter pageId is empty then get list of pages
      operationId: getPage
      parameters:
        - name: pageId
          in: path
          description: identifier of page
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK - it retunrs with a page, if user has access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
        '400':
          description: Invalid ID supplied
          content: {}
        '404':
          description: Page not found
          content: {}

components:
  schemas:
    Page:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pageId:
          type: string
        format:
          type: string
          enum:
            - HTML
            - MD
        text:
          type: string
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /oauth/dialog
          scopes:
            write:pages: modify your pages
            read:pages: read your pages
    api_key:
      type: apiKey
      name: api_key
      in: header


